apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: YWRtaW4xMjM=
  mysql-database: bXlkYg==
  mysql-user: YXBwdXNlcg==
  mysql-password: YXBwcGFzcw==

